import nodeTest from 'node:test'
import assert from 'node:assert/strict'
import { setImmediate as nextTurn } from 'node:timers/promises'
import { headless } from '../helpers/headless.ts'
import { animatedCursor, cursorDib, cursorFile, cursorPng } from '../helpers/cursor-fixtures.ts'
import { inflateImage } from '../../src/backends/files/blob-source.ts'
import { MemorySaveStore } from '../../src/engine/ports/saves.ts'
import type { EngineEvent, SessionDependencies } from '../../src/engine/session.ts'
import type { InputView } from '../../src/engine/ports/input.ts'
import type { CursorImage } from '../../src/formats/cursor/index.ts'

const test = (name: string, run: () => Promise<void>) => nodeTest(name, { timeout: 60000 }, run)
type Definition = Extract<EngineEvent, { type: 'cursor-asset' }>
// The fixed file-loading profile retains one 32x32 RGBA+AND image/frame.
const loadedImageBytes = 5120

function cur(red: number, green: number, blue: number) {
  return cursorFile([{
    width: 1, height: 1,
    payload: cursorDib({ width: 1, height: 1, depth: 24, xorRows: [[blue, green, red]] }),
  }])
}

function directoryImage(
  size: number,
  depth: 24 | 32,
  [red, green, blue]: readonly [number, number, number],
  hotspot: readonly [number, number] = [0, 0],
) {
  const pixel = depth === 32 ? [blue, green, red, 255] : [blue, green, red],
    row = Array.from({ length: size }, () => pixel).flat()
  return {
    width: size, height: size, hotspot,
    payload: cursorDib({ width: size, height: size, depth,
      xorRows: Array.from({ length: size }, () => row) }),
  }
}

function loadedSolid(
  image: CursorImage,
  rgba: readonly [number, number, number, number],
  hotspot = { x: 0, y: 0 },
) {
  assert.equal(image.width, 32)
  assert.equal(image.height, 32)
  assert.deepEqual(image.hotspot, hotspot)
  // Every output pixel is the explicitly specified solid color. This expected
  // plane is independent of the selection and resize implementations.
  assert.deepEqual(image.data, Uint8Array.from({ length: 4096 }, (_, at) => rgba[at % 4]!))
  assert.deepEqual(image.andMask, new Uint8Array(1024))
}

const scene = String.raw`
System.exitOnWindowClose=false;
var win=new Window();win.setInnerSize(160,100);win.visible=true;
var root=new Layer(win,null);root.setSize(160,100);root.fillRect(0,0,160,100,0xff000000);
root.cursor=crArrow;
var parent=new Layer(win,root);parent.setSize(80,80);parent.setPos(10,10);parent.visible=true;
var child=new Layer(win,parent);child.setSize(30,30);child.setPos(5,5);child.visible=true;
child.fillRect(0,0,30,30,0xffffffff);
var other=new Layer(win,root);other.setSize(30,30);other.setPos(110,10);other.visible=true;
other.fillRect(0,0,30,30,0xffffffff);other.cursor=crIBeam;
`

interface Fixture extends Awaited<ReturnType<typeof headless>> {
  windowId: number
  run(name: string): Promise<string>
  move(x?: number, y?: number, shift?: number): Promise<void>
  view(): InputView
  definitions(): Definition[]
}

// The operation functions themselves are in the source/compiled storage, not
// generated by evaluate. No test reads or mutates the Session's Layer maps.
async function withFixture(
  binary: boolean,
  body: string,
  files: Record<string, string | Uint8Array>,
  run: (fixture: Fixture) => Promise<void>,
  overrides: Partial<SessionDependencies> = {},
  release: () => void = () => {},
) {
  const f = await headless({ 'startup.tjs': '', 'custom-cursor.tjs': scene + body, ...files }, overrides)
  let failed = false, primary: unknown
  try {
    await f.session.start()
    if (binary) {
      await f.session.evaluate('Scripts.compileStorage("custom-cursor.tjs","savedata/custom-cursor.cjs",false,true,false)')
      await f.session.evaluate('Scripts.execStorage("savedata/custom-cursor.cjs")')
    } else await f.session.evaluate('Scripts.execStorage("custom-cursor.tjs")')
    await f.session.idle()
    const windowId = Number(await f.session.evaluate('win.__windowId'))
    await run({
      ...f, windowId,
      async run(name) {
        const result = await f.session.evaluate(`${name}()`)
        await f.session.idle()
        return result
      },
      async move(x = 20, y = 20, shift = 0) {
        await f.session.input({ type: 'move', windowId, x, y, shift, button: 0, clicks: 0 })
        await f.session.idle()
      },
      view() {
        for (let i = f.events.length - 1; i >= 0; i--) {
          const event = f.events[i]!
          if (event.type === 'window-input' && event.windowId === windowId) return event.input
        }
        throw new Error('Custom cursor fixture has no Window input view')
      },
      definitions: () => f.events.filter((event): event is Definition => event.type === 'cursor-asset'),
    })
  } catch (error) {
    failed = true
    primary = error
  }
  const cleanupErrors: unknown[] = []
  try { release() } catch (error) { cleanupErrors.push(error) }
  try { await f.session.stop() } catch (error) { cleanupErrors.push(error) }
  try {
    const snapshot = f.session.snapshot()
    assert.equal(snapshot.cursorCacheEntries, 0)
    assert.equal(snapshot.cursorCacheBytes, 0)
    assert.equal(snapshot.cursorCachePending, 0)
    assert.equal(snapshot.handles, 0)
    assert.equal(snapshot.bitmapBytes, 0)
    assert(Object.values(f.session.inspectOwnership()).every((value) => value === 0))
    assert.equal(f.events.filter((event) => event.type === 'cursor-assets-clear').length, 1)
  } catch (error) { cleanupErrors.push(error) }
  if (failed && cleanupErrors.length)
    throw new AggregateError([primary, ...cleanupErrors], 'Custom cursor operation and cleanup failed', { cause: primary })
  if (failed) throw primary
  if (cleanupErrors.length === 1) throw cleanupErrors[0]
  if (cleanupErrors.length) throw new AggregateError(cleanupErrors, 'Custom cursor cleanup failed')
}

function gate() {
  let enter!: () => void, release!: () => void, finish!: () => void
  const entered = new Promise<void>((resolve) => { enter = resolve }),
    held = new Promise<void>((resolve) => { release = resolve }),
    finished = new Promise<void>((resolve) => { finish = resolve })
  return { enter, release, finish, entered, held, finished }
}

function observe<T>(work: Promise<T>) {
  return work.then(
    (value) => ({ status: 'fulfilled' as const, value }),
    (error: unknown) => ({ status: 'rejected' as const, error }),
  )
}

async function enteredGate<T>(entered: Promise<void>, operation: ReturnType<typeof observe<T>>) {
  let timer: ReturnType<typeof setTimeout> | undefined
  try {
    await Promise.race([
      entered,
      operation.then((result) => {
        const cause = result.status === 'rejected' ? result.error : undefined
        throw new Error(`Cursor operation settled before PNG inflate: ${result.status}`, { cause })
      }),
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => reject(new Error('Cursor operation did not enter PNG inflate')), 10000)
      }),
    ])
  } finally { clearTimeout(timer) }
}

for (const binary of [false, true]) {
  const mode = binary ? 'bytecode' : 'source'

  test(`${mode}: numeric-looking cursor strings load resources while nonstrings use native int32`, async () => {
    const numericName = cursorFile([{ width: 1, height: 1, payload: cursorPng(1, 1, [255, 0, 0, 255]) }])
    await withFixture(binary, String.raw`
function path(){child.cursor="42";return child.cursor;}
function numbers(){
  var values=[];
  child.cursor=42;values.add(child.cursor);
  child.cursor=-3.9;values.add(child.cursor);
  child.cursor=0x1fffffffd;values.add(child.cursor);
  child.cursor=true;values.add(child.cursor);
  return values.join(",");
}
function missingNumericPath(){
  child.cursor=crCross;
  try{child.cursor="43";}catch(error){return "caught|"+child.cursor;}
  return "missed|"+child.cursor;
}
`, { '42': numericName }, async (f) => {
      await f.move()
      assert.equal(await f.run('path'), '2')
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('numbers'), '42,-3,-3,1')
      assert.equal(await f.run('missingNumericPath'), 'caught|-3')
      assert.equal(f.view().cursor, -3)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      assert.equal(f.definitions()[0]!.asset.frames[0]!.images[0]!.encoding, 'png')
      loadedSolid(f.definitions()[0]!.asset.frames[0]!.images[0]!, [255, 0, 0, 255])
      assert.equal(f.definitions()[0]!.asset.sourceBytes, numericName.length)
      assert.equal(f.definitions()[0]!.asset.imageCount, 1)
      assert.equal(f.definitions()[0]!.asset.decodedBytes, loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: exact cursor extensions and public auto-path aliases share only their resolved identity`, async () => {
    const red = cur(255, 0, 0), animation = animatedCursor([cur(0, 255, 0), cur(0, 0, 255)], {
      sequence: [1, 0, 1], rates: [3, 6, 9],
    })
    await withFixture(binary, String.raw`
Storages.addAutoPath("art/");
function first(){child.cursor="Pointer.cur";return child.cursor;}
function aliases(){
  var values=[];
  child.cursor="game://./art/./Pointer.cur";values.add(child.cursor);
  child.cursor="ART/POINTER.CUR";values.add(child.cursor);
  return values.join(",");
}
function noExtension(){try{child.cursor="Pointer";}catch(error){return "caught|"+child.cursor;}return "missed";}
function animated(){child.cursor="Pointer.ani";return child.cursor;}
function twin(){child.cursor="copies/Twin.cur";return child.cursor;}
`, { 'art/Pointer.cur': red, 'art/Pointer.ani': animation, 'copies/Twin.cur': red }, async (f) => {
      await f.move()
      assert.equal(await f.run('first'), '2')
      const definitionIndex = f.events.findIndex((event) => event.type === 'cursor-asset' && event.id === 2),
        notifiedIndex = f.events.findIndex((event) => event.type === 'window-input' && event.windowId === f.windowId && event.input.cursor === 2)
      assert(definitionIndex >= 0 && notifiedIndex > definitionIndex, 'Definition precedes the Window cursor ID notification')
      assert.equal(await f.run('aliases'), '2,2')
      assert.equal(await f.run('noExtension'), 'caught|2')
      assert.equal(await f.run('animated'), '3')
      assert.equal(await f.run('twin'), '4')
      const definitions = f.definitions()
      assert.deepEqual(definitions.map((event) => event.id), [2, 3, 4])
      loadedSolid(definitions[0]!.asset.frames[0]!.images[0]!, [255, 0, 0, 255])
      loadedSolid(definitions[2]!.asset.frames[0]!.images[0]!, [255, 0, 0, 255])
      assert.equal(definitions[0]!.asset.sourceBytes, red.length)
      assert.equal(definitions[2]!.asset.sourceBytes, red.length)
      assert.equal(definitions[1]!.asset.kind, 'ani')
      assert.deepEqual(definitions[1]!.asset.sequence, [1, 0, 1])
      assert.deepEqual(definitions[1]!.asset.rates, [3, 6, 9])
      loadedSolid(definitions[1]!.asset.frames[0]!.images[0]!, [0, 255, 0, 255])
      loadedSolid(definitions[1]!.asset.frames[1]!.images[0]!, [0, 0, 255, 255])
      assert.equal(definitions[1]!.asset.sourceBytes, animation.length)
      assert.equal(definitions[1]!.asset.imageCount, 2)
      assert.deepEqual(definitions[1]!.asset.frames.map((frame) => frame.images.length), [1, 1])
      assert.equal(definitions[1]!.asset.decodedBytes, 2 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCacheEntries, 3)
      assert.equal(f.session.snapshot().cursorCacheBytes, 4 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: cursor cache retains old pixels after a real save overwrite but still requires path resolution`, async () => {
    const saveStore = new MemorySaveStore()
    await saveStore.commit([{ path: 'savedata/Cache.cur', bytes: cur(255, 0, 0) }])
    await withFixture(binary, String.raw`
Storages.addAutoPath("savedata/");
function load(){child.cursor="Cache.cur";return child.cursor;}
function overwrite(){["replaced by real text storage"].save("savedata/Cache.cur");return [].load("savedata/Cache.cur")[0];}
function cached(){other.cursor="game://./SAVEDATA/CACHE.CUR";return other.cursor;}
function removeLookup(){
  Storages.removeAutoPath("savedata/");
  try{child.cursor="Cache.cur";}catch(error){return "caught|"+child.cursor;}
  return "missed";
}
function exact(){child.cursor="savedata/Cache.cur";return child.cursor;}
`, {}, async (f) => {
      assert.equal(await f.run('load'), '2')
      assert.equal(await f.run('overwrite'), 'replaced by real text storage')
      assert.equal(await f.run('cached'), '2')
      // Removing the auto-path makes this basename unavailable. Session does
      // not currently expose resource deletion; this does not pretend it does.
      assert.equal(await f.run('removeLookup'), 'caught|2')
      assert.equal(await f.run('exact'), '2')
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      loadedSolid(f.definitions()[0]!.asset.frames[0]!.images[0]!, [255, 0, 0, 255])
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, loadedImageBytes)
    }, { saveStore })
  })

  test(`${mode}: missing and malformed cursor loads preserve the prior value without consuming IDs`, async () => {
    const badPng = cursorPng(1, 1, [10, 20, 30, 255])
    badPng[29] ^= 1
    await withFixture(binary, String.raw`
function before(){
  child.cursor=crCross;var failures=0;
  try{child.cursor="missing.cur";}catch(error){failures++;}
  try{child.cursor="bad.cur";}catch(error){failures++;}
  try{child.cursor="bad-png.cur";}catch(error){failures++;}
  return failures+"|"+child.cursor;
}
function first(){child.cursor="a.cur";return child.cursor;}
function after(){try{child.cursor="bad.cur";}catch(error){return "caught|"+child.cursor;}return "missed";}
function second(){child.cursor="b.cur";return child.cursor;}
`, {
      'bad.cur': new Uint8Array([0, 1, 2]),
      'bad-png.cur': cursorFile([{ width: 1, height: 1, payload: badPng }]),
      'a.cur': cur(255, 0, 0), 'b.cur': cur(0, 255, 0),
    }, async (f) => {
      await f.move()
      assert.equal(await f.run('before'), '3|-3')
      assert.equal(f.view().cursor, -3)
      assert.equal(f.session.snapshot().cursorCacheEntries, 0)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
      assert.deepEqual(f.definitions(), [])
      assert.equal(await f.run('first'), '2')
      assert.equal(await f.run('after'), 'caught|2')
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('second'), '3')
      assert.deepEqual(f.definitions().map((event) => event.id), [2, 3])
      assert.equal(f.session.snapshot().cursorCacheEntries, 2)
      assert.equal(f.session.snapshot().cursorCacheBytes, 2 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: retiring a Layer does not evict its cursor ID and another Layer can reuse that number`, async () => {
    await withFixture(binary, String.raw`
var savedCursor=0;
function load(){child.cursor="a.cur";return child.cursor;}
function retire(){savedCursor=child.cursor;invalidate child;delete global.child;return savedCursor;}
function reuse(){
  global.child=new Layer(win,parent);child.setSize(30,30);child.setPos(5,5);child.visible=true;
  child.fillRect(0,0,30,30,0xffffffff);child.cursor=savedCursor;return child.cursor;
}
`, { 'a.cur': cur(255, 0, 0) }, async (f) => {
      assert.equal(await f.run('load'), '2')
      await f.move()
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('retire'), '2')
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, loadedImageBytes)
      assert.equal(await f.run('reuse'), '2')
      await f.move(120, 20)
      await f.move()
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      assert.equal(f.events.some((event) => event.type === 'cursor-assets-clear'), false)
    })
  })

  test(`${mode}: custom cursor assignment preserves native inheritance and capture notification points`, async () => {
    await withFixture(binary, String.raw`
parent.cursor="a.cur";other.cursor="b.cur";
function changeParent(){parent.cursor="c.cur";return child.cursor;}
function refresh(){child.cursor=0;return child.cursor;}
function otherChange(){other.cursor=2;}
function childChange(){child.cursor=3;}
`, { 'a.cur': cur(255, 0, 0), 'b.cur': cur(0, 255, 0), 'c.cur': cur(0, 0, 255) }, async (f) => {
      await f.move()
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('changeParent'), '0')
      assert.equal(f.view().cursor, 2)
      await f.move(21, 21)
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('refresh'), '0')
      assert.equal(f.view().cursor, 4)
      await f.session.input({ type: 'down', windowId: f.windowId, x: 20, y: 20, shift: 8, button: 0, clicks: 0 })
      await f.move(120, 20, 8)
      await f.run('otherChange')
      assert.equal(f.view().cursor, 4)
      await f.run('childChange')
      assert.equal(f.view().cursor, 3)
      await f.session.input({ type: 'up', windowId: f.windowId, x: 120, y: 20, shift: 0, button: 0, clicks: 0 })
      await f.session.idle()
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2, 3, 4])
      assert.equal(f.session.snapshot().cursorCacheEntries, 3)
      assert.equal(f.session.snapshot().cursorCacheBytes, 3 * loadedImageBytes)
    })
  })

  test(`${mode}: loaded CUR directories choose exact size, then 32-bit depth, and retain the first complete tie`, async () => {
    const small = directoryImage(16, 32, [255, 0, 0], [1, 2]),
      exact = directoryImage(32, 24, [0, 255, 0], [7, 9]),
      large = directoryImage(48, 32, [0, 0, 255], [11, 13]),
      shallow = directoryImage(32, 24, [255, 0, 0], [1, 2]),
      deep = directoryImage(32, 32, [0, 0, 255], [3, 4]),
      tieRed = directoryImage(32, 32, [255, 0, 0], [5, 6]),
      tieGreen = directoryImage(32, 32, [0, 255, 0], [8, 10]),
      files = {
        'size-forward.cur': cursorFile([small, exact, large]),
        'size-reverse.cur': cursorFile([large, exact, small]),
        'depth-forward.cur': cursorFile([shallow, deep]),
        'depth-reverse.cur': cursorFile([deep, shallow]),
        'tie-forward.cur': cursorFile([tieRed, tieGreen]),
        'tie-reverse.cur': cursorFile([tieGreen, tieRed]),
      }
    await withFixture(binary, String.raw`
function directories(){
  var names=["size-forward.cur","size-reverse.cur","depth-forward.cur","depth-reverse.cur","tie-forward.cur","tie-reverse.cur"],ids=[];
  for(var i=0;i<names.count;i++){child.cursor=names[i];ids.add(child.cursor);}
  return ids.join(",");
}
`, files, async (f) => {
      assert.equal(await f.run('directories'), '2,3,4,5,6,7')
      const definitions = f.definitions(),
        expected = [
          { color: [0, 255, 0, 255], hotspot: { x: 7, y: 9 }, depth: 24, source: files['size-forward.cur'] },
          { color: [0, 255, 0, 255], hotspot: { x: 7, y: 9 }, depth: 24, source: files['size-reverse.cur'] },
          { color: [0, 0, 255, 255], hotspot: { x: 3, y: 4 }, depth: 32, source: files['depth-forward.cur'] },
          { color: [0, 0, 255, 255], hotspot: { x: 3, y: 4 }, depth: 32, source: files['depth-reverse.cur'] },
          { color: [255, 0, 0, 255], hotspot: { x: 5, y: 6 }, depth: 32, source: files['tie-forward.cur'] },
          { color: [0, 255, 0, 255], hotspot: { x: 8, y: 10 }, depth: 32, source: files['tie-reverse.cur'] },
        ] as const
      assert.deepEqual(definitions.map((event) => event.id), [2, 3, 4, 5, 6, 7])
      for (let at = 0; at < expected.length; at++) {
        const asset = definitions[at]!.asset, reference = expected[at]!
        assert.equal(asset.kind, 'cur')
        assert.equal(asset.frames.length, 1)
        assert.equal(asset.frames[0]!.images.length, 1)
        assert.equal(asset.imageCount, 1)
        assert.equal(asset.decodedBytes, loadedImageBytes)
        assert.equal(asset.sourceBytes, reference.source.length)
        const selected = asset.frames[0]!.images[0]!
        loadedSolid(selected, reference.color, reference.hotspot)
        assert.equal(selected.depth, reference.depth)
      }
      assert.equal(f.session.snapshot().cursorCacheEntries, 6)
      assert.equal(f.session.snapshot().cursorCacheBytes, 6 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: loaded ANI selects each frame independently while preserving its entire repeated sequence`, async () => {
    const frame0 = cursorFile([
        directoryImage(16, 32, [255, 0, 0]),
        directoryImage(32, 24, [0, 255, 0], [2, 3]),
        directoryImage(48, 32, [0, 0, 255]),
      ]),
      frame1 = cursorFile([
        directoryImage(32, 24, [255, 255, 0], [4, 5]),
        directoryImage(32, 32, [255, 0, 255], [6, 7]),
      ]),
      frame2 = cursorFile([
        directoryImage(32, 32, [0, 255, 255], [8, 9]),
        directoryImage(32, 32, [255, 255, 255], [10, 11]),
      ]),
      animation = animatedCursor([frame0, frame1, frame2], {
        sequence: [2, 0, 2, 1, 0], rates: [3, 6, 9, 12, 15],
      })
    await withFixture(binary, String.raw`
function loadAnimation(){child.cursor="choices.ani";return child.cursor;}
`, { 'choices.ani': animation }, async (f) => {
      await f.move()
      assert.equal(await f.run('loadAnimation'), '2')
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      const asset = f.definitions()[0]!.asset
      assert.equal(asset.kind, 'ani')
      assert.equal(asset.frames.length, 3)
      assert.deepEqual(asset.frames.map((frame) => frame.images.length), [1, 1, 1])
      assert.deepEqual(asset.frames.map((frame) => frame.images[0]!.depth), [24, 32, 32])
      loadedSolid(asset.frames[0]!.images[0]!, [0, 255, 0, 255], { x: 2, y: 3 })
      loadedSolid(asset.frames[1]!.images[0]!, [255, 0, 255, 255], { x: 6, y: 7 })
      loadedSolid(asset.frames[2]!.images[0]!, [0, 255, 255, 255], { x: 8, y: 9 })
      assert.deepEqual(asset.sequence, [2, 0, 2, 1, 0])
      assert.deepEqual(asset.rates, [3, 6, 9, 12, 15])
      assert.equal(asset.durationJiffies, 45)
      assert.deepEqual(asset.sequence.map((index) => [...asset.frames[index]!.images[0]!.data.subarray(0, 4)]), [
        [0, 255, 255, 255], [0, 255, 0, 255], [0, 255, 255, 255],
        [255, 0, 255, 255], [0, 255, 0, 255],
      ])
      assert.equal(asset.sourceBytes, animation.length)
      assert.equal(asset.imageCount, 3)
      assert.equal(asset.decodedBytes, 3 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, 3 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: a one-frame one-step ANI loads as a static native timeline and remains assignable`, async () => {
    const animation = animatedCursor([
      cursorFile([directoryImage(32, 32, [0, 255, 255], [2, 3])]),
    ], { defaultRate: 9 })
    await withFixture(binary, String.raw`
function loadSingle(){child.cursor="single.ani";return child.cursor;}
function reuseSingle(){other.cursor=child.cursor;return other.cursor;}
`, { 'single.ani': animation }, async (f) => {
      await f.move()
      assert.equal(await f.run('loadSingle'), '2')
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      const asset = f.definitions()[0]!.asset
      assert.equal(asset.kind, 'ani')
      assert.deepEqual(asset.sequence, [0])
      // 081 observations on both Windows runners report rate 0 / steps 1
      // for the one-frame ANI whose source header has default rate 9.
      assert.deepEqual(asset.rates, [0])
      assert.equal(asset.durationJiffies, 0)
      assert.equal(asset.frames.length, 1)
      assert.equal(asset.frames[0]!.images.length, 1)
      loadedSolid(asset.frames[0]!.images[0]!, [0, 255, 255, 255], { x: 2, y: 3 })
      assert.equal(asset.sourceBytes, animation.length)
      assert.equal(asset.imageCount, 1)
      assert.equal(asset.decodedBytes, loadedImageBytes)
      assert.equal(await f.run('reuseSingle'), '2')
      await f.move(120, 20)
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: CUR and ANI ignore damaged unselected alternatives but never fall back from a damaged selected image`, async () => {
    const small = directoryImage(16, 32, [255, 0, 0]),
      exact = directoryImage(32, 32, [0, 255, 0]),
      brokenSmall = { ...small, payload: small.payload.subarray(0, 40) },
      brokenExact = { ...exact, payload: exact.payload.subarray(0, 40) },
      goodForward = cursorFile([brokenSmall, exact]),
      goodReverse = cursorFile([exact, brokenSmall]),
      badForward = cursorFile([brokenExact, small]),
      badReverse = cursorFile([small, brokenExact]),
      blue = cursorFile([directoryImage(32, 32, [0, 0, 255])]),
      goodAniForward = animatedCursor([goodForward, blue], { sequence: [1, 0, 1], rates: [2, 3, 4] }),
      goodAniReverse = animatedCursor([goodReverse, blue], { sequence: [1, 0, 1], rates: [2, 3, 4] }),
      files = {
        'unselected-forward.cur': goodForward,
        'unselected-reverse.cur': goodReverse,
        'unselected-forward.ani': goodAniForward,
        'unselected-reverse.ani': goodAniReverse,
        'selected-forward.cur': badForward,
        'selected-reverse.cur': badReverse,
        // A complete first frame must not publish a partially loaded ANI if
        // the selected image in its second frame is damaged.
        'selected-forward.ani': animatedCursor([blue, badForward]),
        'selected-reverse.ani': animatedCursor([blue, badReverse]),
        'after.cur': cursorFile([directoryImage(32, 32, [255, 255, 0])]),
      }
    await withFixture(binary, String.raw`
function unselected(){
  var names=["unselected-forward.cur","unselected-reverse.cur","unselected-forward.ani","unselected-reverse.ani"],ids=[];
  for(var i=0;i<names.count;i++){child.cursor=names[i];ids.add(child.cursor);}
  return ids.join(",");
}
function selected(){
  var names=["selected-forward.cur","selected-reverse.cur","selected-forward.ani","selected-reverse.ani"],states=[];
  for(var i=0;i<names.count;i++){
    if(!Storages.isExistentStorage(names[i]))throw new Exception("missing cursor fixture: "+names[i]);
    try{child.cursor=names[i];states.add("accepted|"+child.cursor);}
    catch(error){states.add("caught|"+child.cursor);}
  }
  return states.join(",");
}
function afterwards(){child.cursor="after.cur";return child.cursor;}
`, files, async (f) => {
      await f.move()
      assert.equal(await f.run('unselected'), '2,3,4,5')
      assert.equal(f.view().cursor, 5)
      const definitions = f.definitions()
      assert.deepEqual(definitions.map((event) => event.id), [2, 3, 4, 5])
      for (const index of [0, 1]) {
        const asset = definitions[index]!.asset
        assert.equal(asset.kind, 'cur')
        assert.deepEqual(asset.frames.map((frame) => frame.images.length), [1])
        loadedSolid(asset.frames[0]!.images[0]!, [0, 255, 0, 255])
      }
      for (const index of [2, 3]) {
        const asset = definitions[index]!.asset
        assert.equal(asset.kind, 'ani')
        assert.deepEqual(asset.frames.map((frame) => frame.images.length), [1, 1])
        loadedSolid(asset.frames[0]!.images[0]!, [0, 255, 0, 255])
        loadedSolid(asset.frames[1]!.images[0]!, [0, 0, 255, 255])
        assert.deepEqual(asset.sequence, [1, 0, 1])
        assert.deepEqual(asset.rates, [2, 3, 4])
        assert.equal(asset.imageCount, 2)
        assert.equal(asset.decodedBytes, 2 * loadedImageBytes)
      }
      assert.deepEqual(definitions.map((event) => event.asset.sourceBytes), [
        goodForward.length, goodReverse.length, goodAniForward.length, goodAniReverse.length,
      ])
      assert.equal(await f.run('selected'), 'caught|5,caught|5,caught|5,caught|5')
      assert.equal(f.view().cursor, 5)
      assert.deepEqual(f.definitions().map((event) => event.id), [2, 3, 4, 5])
      assert.equal(f.session.snapshot().cursorCacheEntries, 4)
      assert.equal(f.session.snapshot().cursorCacheBytes, 6 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
      assert.equal(await f.run('afterwards'), '6')
      assert.equal(f.view().cursor, 6)
      assert.deepEqual(f.definitions().map((event) => event.id), [2, 3, 4, 5, 6])
      loadedSolid(f.definitions()[4]!.asset.frames[0]!.images[0]!, [255, 255, 0, 255])
      assert.equal(f.session.snapshot().cursorCacheEntries, 5)
      assert.equal(f.session.snapshot().cursorCacheBytes, 7 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: CUR and ANI events retain native DWORD hotspots without enlarging their loaded pixel planes`, async () => {
    const natural = cursorFile([directoryImage(32, 32, [0, 255, 0], [65535, 32768])]),
      small = cursorFile([{
        width: 8, height: 4, hotspot: [65535, 32768],
        payload: cursorDib({ width: 8, height: 4, depth: 32,
          xorRows: Array.from({ length: 4 }, () => Array.from({ length: 8 }, () => [0, 0, 0, 255]).flat()) }),
      }]),
      animation = animatedCursor([natural, small], { sequence: [1, 0, 1], rates: [3, 6, 9] })
    await withFixture(binary, String.raw`
function natural(){child.cursor="wide-natural.cur";return child.cursor;}
function small(){child.cursor="wide-small.cur";return child.cursor;}
function animated(){child.cursor="wide.ani";return child.cursor;}
`, { 'wide-natural.cur': natural, 'wide-small.cur': small, 'wide.ani': animation }, async (f) => {
      assert.equal(await f.run('natural'), '2')
      assert.equal(await f.run('small'), '3')
      assert.equal(await f.run('animated'), '4')
      const definitions = f.definitions(),
        // Literal DWORD results recorded by 081 GetIconInfo observations.
        // Neither the decoder nor the loading policy computes these expectations.
        naturalHotspot = { x: 0, y: 4294934529 },
        smallHotspot = { x: 4294967293, y: 1 },
        expectedHotspots = [[naturalHotspot], [smallHotspot], [naturalHotspot, smallHotspot]]
      assert.deepEqual(definitions.map((event) => event.id), [2, 3, 4])
      assert.deepEqual(definitions.map((event) => event.asset.sourceBytes), [natural.length, small.length, animation.length])
      for (let index = 0; index < definitions.length; index++) {
        const asset = definitions[index]!.asset, expected = expectedHotspots[index]!
        assert.equal(asset.frames.length, expected.length)
        assert.equal(asset.imageCount, expected.length)
        assert.equal(asset.decodedBytes, expected.length * loadedImageBytes)
        for (let frame = 0; frame < expected.length; frame++) {
          assert.equal(asset.frames[frame]!.images.length, 1)
          const image = asset.frames[frame]!.images[0]!
          assert.deepEqual(image.hotspot, expected[frame])
          assert.equal(image.width, 32)
          assert.equal(image.height, 32)
          assert.equal(image.data.byteLength, 4096)
          assert.equal(image.andMask.byteLength, 1024)
        }
      }
      loadedSolid(definitions[0]!.asset.frames[0]!.images[0]!, [0, 255, 0, 255], naturalHotspot)
      assert.deepEqual(definitions[2]!.asset.sequence, [1, 0, 1])
      assert.deepEqual(definitions[2]!.asset.rates, [3, 6, 9])
      assert.equal(f.session.snapshot().cursorCacheEntries, 3)
      assert.equal(f.session.snapshot().cursorCacheBytes, 4 * loadedImageBytes)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  for (const outcome of ['resolve', 'reject'] as const) {
    test(`${mode}: Stop clears cursor assets before suspended PNG inflate can ${outcome} late`, async () => {
      const blocked = gate(), lateError = new Error('late cursor inflate failure')
      await withFixture(binary, String.raw`
child.cursor="a.cur";
function held(){child.cursor="waiting.cur";Debug.message("custom-cursor-tail");return child.cursor;}
`, {
        'a.cur': cur(255, 0, 0),
        'waiting.cur': cursorFile([{ width: 1, height: 1, payload: cursorPng(1, 1, [0, 255, 0, 128]) }]),
      }, async (f) => {
        const operation = observe(f.run('held'))
        await enteredGate(blocked.entered, operation)
        assert.equal(f.session.snapshot().cursorCacheEntries, 1)
        assert.equal(f.session.snapshot().cursorCacheBytes, loadedImageBytes)
        assert.equal(f.session.snapshot().cursorCachePending, 1)
        assert.deepEqual(f.definitions().map((event) => event.id), [2])
        // Stop must settle while the real inflater is still held; releasing it
        // first would hide a cancellation dependency on the late decoder.
        await f.session.stop()
        const stopped = await operation
        assert.equal(stopped.status, 'rejected')
        if (stopped.status === 'rejected') assert.match(String(stopped.error), /cancelled/i)
        assert.equal(f.session.snapshot().state, 'stopped')
        assert.equal(f.session.snapshot().cursorCacheEntries, 0)
        assert.equal(f.session.snapshot().cursorCacheBytes, 0)
        assert.equal(f.session.snapshot().cursorCachePending, 0)
        assert.equal(f.events.filter((event) => event.type === 'cursor-assets-clear').length, 1)
        blocked.release()
        await blocked.finished
        await nextTurn()
        await f.session.idle()
        assert.deepEqual(f.definitions().map((event) => event.id), [2])
        assert.equal(f.logs.includes('custom-cursor-tail'), false)
        assert.equal(f.session.snapshot().cursorCacheEntries, 0)
        assert.equal(f.session.snapshot().cursorCacheBytes, 0)
        assert.equal(f.session.snapshot().cursorCachePending, 0)
        const cleared = f.events.findIndex((event) => event.type === 'cursor-assets-clear')
        assert.equal(f.events.slice(cleared + 1).some((event) => event.type === 'cursor-asset'), false)
      }, {
        async inflateImage(bytes, expectedLength) {
          blocked.enter()
          try {
            await blocked.held
            if (outcome === 'reject') throw lateError
            return await inflateImage(bytes, expectedLength)
          } finally { blocked.finish() }
        },
      }, blocked.release)
    })
  }
}
