import nodeTest from 'node:test'
import assert from 'node:assert/strict'
import { setImmediate as nextTurn } from 'node:timers/promises'
import { headless } from '../helpers/headless.ts'
import { animatedCursor, cursorDib, cursorFile, cursorPng } from '../helpers/cursor-fixtures.ts'
import { inflateImage } from '../../src/backends/files/blob-source.ts'
import { MemorySaveStore } from '../../src/engine/ports/saves.ts'
import type { EngineEvent, SessionDependencies } from '../../src/engine/session.ts'
import type { InputView } from '../../src/engine/ports/input.ts'

const test = (name: string, run: () => Promise<void>) => nodeTest(name, { timeout: 60000 }, run)
type Definition = Extract<EngineEvent, { type: 'cursor-asset' }>

function cur(red: number, green: number, blue: number) {
  return cursorFile([{
    width: 1, height: 1,
    payload: cursorDib({ width: 1, height: 1, depth: 24, xorRows: [[blue, green, red]] }),
  }])
}

const scene = String.raw`
System.exitOnWindowClose=false;
var win=new Window();win.setInnerSize(160,100);win.visible=true;
var root=new Layer(win,null);root.setSize(160,100);root.fillRect(0,0,160,100,0xff000000);
root.cursor=crArrow;
var parent=new Layer(win,root);parent.setSize(80,80);parent.setPos(10,10);parent.visible=true;
var child=new Layer(win,parent);child.setSize(30,30);child.setPos(5,5);child.visible=true;
child.fillRect(0,0,30,30,0xffffffff);
var other=new Layer(win,root);other.setSize(30,30);other.setPos(110,10);other.visible=true;
other.fillRect(0,0,30,30,0xffffffff);other.cursor=crIBeam;
`

interface Fixture extends Awaited<ReturnType<typeof headless>> {
  windowId: number
  run(name: string): Promise<string>
  move(x?: number, y?: number, shift?: number): Promise<void>
  view(): InputView
  definitions(): Definition[]
}

// The operation functions themselves are in the source/compiled storage, not
// generated by evaluate. No test reads or mutates the Session's Layer maps.
async function withFixture(
  binary: boolean,
  body: string,
  files: Record<string, string | Uint8Array>,
  run: (fixture: Fixture) => Promise<void>,
  overrides: Partial<SessionDependencies> = {},
  release: () => void = () => {},
) {
  const f = await headless({ 'startup.tjs': '', 'custom-cursor.tjs': scene + body, ...files }, overrides)
  let failed = false, primary: unknown
  try {
    await f.session.start()
    if (binary) {
      await f.session.evaluate('Scripts.compileStorage("custom-cursor.tjs","savedata/custom-cursor.cjs",false,true,false)')
      await f.session.evaluate('Scripts.execStorage("savedata/custom-cursor.cjs")')
    } else await f.session.evaluate('Scripts.execStorage("custom-cursor.tjs")')
    await f.session.idle()
    const windowId = Number(await f.session.evaluate('win.__windowId'))
    await run({
      ...f, windowId,
      async run(name) {
        const result = await f.session.evaluate(`${name}()`)
        await f.session.idle()
        return result
      },
      async move(x = 20, y = 20, shift = 0) {
        await f.session.input({ type: 'move', windowId, x, y, shift, button: 0, clicks: 0 })
        await f.session.idle()
      },
      view() {
        for (let i = f.events.length - 1; i >= 0; i--) {
          const event = f.events[i]!
          if (event.type === 'window-input' && event.windowId === windowId) return event.input
        }
        throw new Error('Custom cursor fixture has no Window input view')
      },
      definitions: () => f.events.filter((event): event is Definition => event.type === 'cursor-asset'),
    })
  } catch (error) {
    failed = true
    primary = error
  }
  const cleanupErrors: unknown[] = []
  try { release() } catch (error) { cleanupErrors.push(error) }
  try { await f.session.stop() } catch (error) { cleanupErrors.push(error) }
  try {
    const snapshot = f.session.snapshot()
    assert.equal(snapshot.cursorCacheEntries, 0)
    assert.equal(snapshot.cursorCacheBytes, 0)
    assert.equal(snapshot.cursorCachePending, 0)
    assert.equal(snapshot.handles, 0)
    assert.equal(snapshot.bitmapBytes, 0)
    assert(Object.values(f.session.inspectOwnership()).every((value) => value === 0))
    assert.equal(f.events.filter((event) => event.type === 'cursor-assets-clear').length, 1)
  } catch (error) { cleanupErrors.push(error) }
  if (failed && cleanupErrors.length)
    throw new AggregateError([primary, ...cleanupErrors], 'Custom cursor operation and cleanup failed', { cause: primary })
  if (failed) throw primary
  if (cleanupErrors.length === 1) throw cleanupErrors[0]
  if (cleanupErrors.length) throw new AggregateError(cleanupErrors, 'Custom cursor cleanup failed')
}

function gate() {
  let enter!: () => void, release!: () => void, finish!: () => void
  const entered = new Promise<void>((resolve) => { enter = resolve }),
    held = new Promise<void>((resolve) => { release = resolve }),
    finished = new Promise<void>((resolve) => { finish = resolve })
  return { enter, release, finish, entered, held, finished }
}

function observe<T>(work: Promise<T>) {
  return work.then(
    (value) => ({ status: 'fulfilled' as const, value }),
    (error: unknown) => ({ status: 'rejected' as const, error }),
  )
}

async function enteredGate<T>(entered: Promise<void>, operation: ReturnType<typeof observe<T>>) {
  let timer: ReturnType<typeof setTimeout> | undefined
  try {
    await Promise.race([
      entered,
      operation.then((result) => {
        const cause = result.status === 'rejected' ? result.error : undefined
        throw new Error(`Cursor operation settled before PNG inflate: ${result.status}`, { cause })
      }),
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => reject(new Error('Cursor operation did not enter PNG inflate')), 10000)
      }),
    ])
  } finally { clearTimeout(timer) }
}

for (const binary of [false, true]) {
  const mode = binary ? 'bytecode' : 'source'

  test(`${mode}: numeric-looking cursor strings load resources while nonstrings use native int32`, async () => {
    await withFixture(binary, String.raw`
function path(){child.cursor="42";return child.cursor;}
function numbers(){
  var values=[];
  child.cursor=42;values.add(child.cursor);
  child.cursor=-3.9;values.add(child.cursor);
  child.cursor=0x1fffffffd;values.add(child.cursor);
  child.cursor=true;values.add(child.cursor);
  return values.join(",");
}
function missingNumericPath(){
  child.cursor=crCross;
  try{child.cursor="43";}catch(error){return "caught|"+child.cursor;}
  return "missed|"+child.cursor;
}
`, { '42': cursorFile([{ width: 1, height: 1, payload: cursorPng(1, 1, [255, 0, 0, 255]) }]) }, async (f) => {
      await f.move()
      assert.equal(await f.run('path'), '2')
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('numbers'), '42,-3,-3,1')
      assert.equal(await f.run('missingNumericPath'), 'caught|-3')
      assert.equal(f.view().cursor, -3)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      assert.equal(f.definitions()[0]!.asset.frames[0]!.images[0]!.encoding, 'png')
      assert.deepEqual([...f.definitions()[0]!.asset.frames[0]!.images[0]!.data], [255, 0, 0, 255])
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, 5)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: exact cursor extensions and public auto-path aliases share only their resolved identity`, async () => {
    const red = cur(255, 0, 0), animation = animatedCursor([cur(0, 255, 0), cur(0, 0, 255)], {
      sequence: [1, 0, 1], rates: [3, 6, 9],
    })
    await withFixture(binary, String.raw`
Storages.addAutoPath("art/");
function first(){child.cursor="Pointer.cur";return child.cursor;}
function aliases(){
  var values=[];
  child.cursor="game://./art/./Pointer.cur";values.add(child.cursor);
  child.cursor="ART/POINTER.CUR";values.add(child.cursor);
  return values.join(",");
}
function noExtension(){try{child.cursor="Pointer";}catch(error){return "caught|"+child.cursor;}return "missed";}
function animated(){child.cursor="Pointer.ani";return child.cursor;}
function twin(){child.cursor="copies/Twin.cur";return child.cursor;}
`, { 'art/Pointer.cur': red, 'art/Pointer.ani': animation, 'copies/Twin.cur': red }, async (f) => {
      await f.move()
      assert.equal(await f.run('first'), '2')
      const definitionIndex = f.events.findIndex((event) => event.type === 'cursor-asset' && event.id === 2),
        notifiedIndex = f.events.findIndex((event) => event.type === 'window-input' && event.windowId === f.windowId && event.input.cursor === 2)
      assert(definitionIndex >= 0 && notifiedIndex > definitionIndex, 'Definition precedes the Window cursor ID notification')
      assert.equal(await f.run('aliases'), '2,2')
      assert.equal(await f.run('noExtension'), 'caught|2')
      assert.equal(await f.run('animated'), '3')
      assert.equal(await f.run('twin'), '4')
      const definitions = f.definitions()
      assert.deepEqual(definitions.map((event) => event.id), [2, 3, 4])
      assert.deepEqual([...definitions[0]!.asset.frames[0]!.images[0]!.data], [255, 0, 0, 255])
      assert.deepEqual([...definitions[2]!.asset.frames[0]!.images[0]!.data], [255, 0, 0, 255])
      assert.equal(definitions[1]!.asset.kind, 'ani')
      assert.deepEqual(definitions[1]!.asset.sequence, [1, 0, 1])
      assert.deepEqual(definitions[1]!.asset.rates, [3, 6, 9])
      assert.deepEqual([...definitions[1]!.asset.frames[0]!.images[0]!.data], [0, 255, 0, 255])
      assert.deepEqual([...definitions[1]!.asset.frames[1]!.images[0]!.data], [0, 0, 255, 255])
      assert.equal(f.session.snapshot().cursorCacheEntries, 3)
      assert.equal(f.session.snapshot().cursorCacheBytes, 20)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: cursor cache retains old pixels after a real save overwrite but still requires path resolution`, async () => {
    const saveStore = new MemorySaveStore()
    await saveStore.commit([{ path: 'savedata/Cache.cur', bytes: cur(255, 0, 0) }])
    await withFixture(binary, String.raw`
Storages.addAutoPath("savedata/");
function load(){child.cursor="Cache.cur";return child.cursor;}
function overwrite(){["replaced by real text storage"].save("savedata/Cache.cur");return [].load("savedata/Cache.cur")[0];}
function cached(){other.cursor="game://./SAVEDATA/CACHE.CUR";return other.cursor;}
function removeLookup(){
  Storages.removeAutoPath("savedata/");
  try{child.cursor="Cache.cur";}catch(error){return "caught|"+child.cursor;}
  return "missed";
}
function exact(){child.cursor="savedata/Cache.cur";return child.cursor;}
`, {}, async (f) => {
      assert.equal(await f.run('load'), '2')
      assert.equal(await f.run('overwrite'), 'replaced by real text storage')
      assert.equal(await f.run('cached'), '2')
      // Removing the auto-path makes this basename unavailable. Session does
      // not currently expose resource deletion; this does not pretend it does.
      assert.equal(await f.run('removeLookup'), 'caught|2')
      assert.equal(await f.run('exact'), '2')
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      assert.deepEqual([...f.definitions()[0]!.asset.frames[0]!.images[0]!.data], [255, 0, 0, 255])
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, 5)
    }, { saveStore })
  })

  test(`${mode}: missing and malformed cursor loads preserve the prior value without consuming IDs`, async () => {
    const badPng = cursorPng(1, 1, [10, 20, 30, 255])
    badPng[29] ^= 1
    await withFixture(binary, String.raw`
function before(){
  child.cursor=crCross;var failures=0;
  try{child.cursor="missing.cur";}catch(error){failures++;}
  try{child.cursor="bad.cur";}catch(error){failures++;}
  try{child.cursor="bad-png.cur";}catch(error){failures++;}
  return failures+"|"+child.cursor;
}
function first(){child.cursor="a.cur";return child.cursor;}
function after(){try{child.cursor="bad.cur";}catch(error){return "caught|"+child.cursor;}return "missed";}
function second(){child.cursor="b.cur";return child.cursor;}
`, {
      'bad.cur': new Uint8Array([0, 1, 2]),
      'bad-png.cur': cursorFile([{ width: 1, height: 1, payload: badPng }]),
      'a.cur': cur(255, 0, 0), 'b.cur': cur(0, 255, 0),
    }, async (f) => {
      await f.move()
      assert.equal(await f.run('before'), '3|-3')
      assert.equal(f.view().cursor, -3)
      assert.equal(f.session.snapshot().cursorCacheEntries, 0)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
      assert.deepEqual(f.definitions(), [])
      assert.equal(await f.run('first'), '2')
      assert.equal(await f.run('after'), 'caught|2')
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('second'), '3')
      assert.deepEqual(f.definitions().map((event) => event.id), [2, 3])
      assert.equal(f.session.snapshot().cursorCacheEntries, 2)
      assert.equal(f.session.snapshot().cursorCacheBytes, 10)
      assert.equal(f.session.snapshot().cursorCachePending, 0)
    })
  })

  test(`${mode}: retiring a Layer does not evict its cursor ID and another Layer can reuse that number`, async () => {
    await withFixture(binary, String.raw`
var savedCursor=0;
function load(){child.cursor="a.cur";return child.cursor;}
function retire(){savedCursor=child.cursor;invalidate child;delete global.child;return savedCursor;}
function reuse(){
  global.child=new Layer(win,parent);child.setSize(30,30);child.setPos(5,5);child.visible=true;
  child.fillRect(0,0,30,30,0xffffffff);child.cursor=savedCursor;return child.cursor;
}
`, { 'a.cur': cur(255, 0, 0) }, async (f) => {
      assert.equal(await f.run('load'), '2')
      await f.move()
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('retire'), '2')
      assert.equal(f.session.snapshot().cursorCacheEntries, 1)
      assert.equal(f.session.snapshot().cursorCacheBytes, 5)
      assert.equal(await f.run('reuse'), '2')
      await f.move(120, 20)
      await f.move()
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2])
      assert.equal(f.events.some((event) => event.type === 'cursor-assets-clear'), false)
    })
  })

  test(`${mode}: custom cursor assignment preserves native inheritance and capture notification points`, async () => {
    await withFixture(binary, String.raw`
parent.cursor="a.cur";other.cursor="b.cur";
function changeParent(){parent.cursor="c.cur";return child.cursor;}
function refresh(){child.cursor=0;return child.cursor;}
function otherChange(){other.cursor=2;}
function childChange(){child.cursor=3;}
`, { 'a.cur': cur(255, 0, 0), 'b.cur': cur(0, 255, 0), 'c.cur': cur(0, 0, 255) }, async (f) => {
      await f.move()
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('changeParent'), '0')
      assert.equal(f.view().cursor, 2)
      await f.move(21, 21)
      assert.equal(f.view().cursor, 2)
      assert.equal(await f.run('refresh'), '0')
      assert.equal(f.view().cursor, 4)
      await f.session.input({ type: 'down', windowId: f.windowId, x: 20, y: 20, shift: 8, button: 0, clicks: 0 })
      await f.move(120, 20, 8)
      await f.run('otherChange')
      assert.equal(f.view().cursor, 4)
      await f.run('childChange')
      assert.equal(f.view().cursor, 3)
      await f.session.input({ type: 'up', windowId: f.windowId, x: 120, y: 20, shift: 0, button: 0, clicks: 0 })
      await f.session.idle()
      assert.equal(f.view().cursor, 2)
      assert.deepEqual(f.definitions().map((event) => event.id), [2, 3, 4])
      assert.equal(f.session.snapshot().cursorCacheEntries, 3)
    })
  })

  for (const outcome of ['resolve', 'reject'] as const) {
    test(`${mode}: Stop clears cursor assets before suspended PNG inflate can ${outcome} late`, async () => {
      const blocked = gate(), lateError = new Error('late cursor inflate failure')
      await withFixture(binary, String.raw`
child.cursor="a.cur";
function held(){child.cursor="waiting.cur";Debug.message("custom-cursor-tail");return child.cursor;}
`, {
        'a.cur': cur(255, 0, 0),
        'waiting.cur': cursorFile([{ width: 1, height: 1, payload: cursorPng(1, 1, [0, 255, 0, 128]) }]),
      }, async (f) => {
        const operation = observe(f.run('held'))
        await enteredGate(blocked.entered, operation)
        assert.equal(f.session.snapshot().cursorCacheEntries, 1)
        assert.equal(f.session.snapshot().cursorCacheBytes, 5)
        assert.equal(f.session.snapshot().cursorCachePending, 1)
        assert.deepEqual(f.definitions().map((event) => event.id), [2])
        // Stop must settle while the real inflater is still held; releasing it
        // first would hide a cancellation dependency on the late decoder.
        await f.session.stop()
        const stopped = await operation
        assert.equal(stopped.status, 'rejected')
        if (stopped.status === 'rejected') assert.match(String(stopped.error), /cancelled/i)
        assert.equal(f.session.snapshot().state, 'stopped')
        assert.equal(f.session.snapshot().cursorCacheEntries, 0)
        assert.equal(f.session.snapshot().cursorCacheBytes, 0)
        assert.equal(f.session.snapshot().cursorCachePending, 0)
        assert.equal(f.events.filter((event) => event.type === 'cursor-assets-clear').length, 1)
        blocked.release()
        await blocked.finished
        await nextTurn()
        await f.session.idle()
        assert.deepEqual(f.definitions().map((event) => event.id), [2])
        assert.equal(f.logs.includes('custom-cursor-tail'), false)
        assert.equal(f.session.snapshot().cursorCacheEntries, 0)
        assert.equal(f.session.snapshot().cursorCacheBytes, 0)
        assert.equal(f.session.snapshot().cursorCachePending, 0)
        const cleared = f.events.findIndex((event) => event.type === 'cursor-assets-clear')
        assert.equal(f.events.slice(cleared + 1).some((event) => event.type === 'cursor-asset'), false)
      }, {
        async inflateImage(bytes, expectedLength) {
          blocked.enter()
          try {
            await blocked.held
            if (outcome === 'reject') throw lateError
            return await inflateImage(bytes, expectedLength)
          } finally { blocked.finish() }
        },
      }, blocked.release)
    })
  }
}
