"""Generate deterministic BMP vertical orientation and presentation fallbacks."""
import hashlib,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
DATA=ROOT/'third_party/unicode'
orientation=DATA/'VerticalOrientation-17.0.0.txt'
unicode=DATA/'UnicodeData-17.0.0.txt'
values=['R']*65536
for line in orientation.read_text().splitlines():
 line=line.split('#')[0].strip()
 if not line:continue
 code,value=[p.strip() for p in line.split(';')]
 first,*last=code.split('..');a=int(first,16);b=int(last[0],16) if last else a
 for c in range(a,min(b,65535)+1):values[c]=value
ranges=[]
for code,value in enumerate(values):
 if value=='R':continue
 if ranges and ranges[-1][1]+1==code and ranges[-1][2]==value:ranges[-1][1]=code
 else:ranges.append([code,code,value])
fallbacks={};wide={}
for line in unicode.read_text().splitlines():
 fields=line.split(';');code=int(fields[0],16);decomposition=fields[5].split()
 if len(decomposition)!=2:continue
 if decomposition[0]=='<vertical>':fallbacks[int(decomposition[1],16)]=code
 if decomposition[0]=='<wide>':wide[code]=int(decomposition[1],16)
for code,base in wide.items():
 if base in fallbacks:fallbacks[code]=fallbacks[base]
fallbacks={c:v for c,v in fallbacks.items() if c<65536 and values[c] in ['Tu','Tr']}
def js(value):return json.dumps(value,ensure_ascii=True,separators=(',',':'))
target=ROOT/'src/formats/font/vertical-data.ts'
target.write_text('// Generated by scripts/generate-vertical-data.py from Unicode 17.0.0.\n'
 '// Unicode License V3: third_party/unicode/LICENSE.txt and public/licenses/unicode/LICENSE.txt.\n'
 'export const verticalRanges: readonly (readonly [number, number, "U" | "Tu" | "Tr"])[] = '+js(ranges)+'\n'
 'export const verticalFallbacks: ReadonlyMap<number, number> = new Map('+js(sorted(fallbacks.items()))+')\n')
(ROOT/'tests/fixtures/text-layout/unicode.json').write_text(json.dumps({'version':'17.0.0','rangeCount':len(ranges),'fallbackCount':len(fallbacks),
 'sources':{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [orientation,unicode,DATA/'LICENSE.txt']}},indent=2)+'\n')
license=ROOT/'public/licenses/unicode/LICENSE.txt';license.parent.mkdir(parents=True,exist_ok=True);license.write_bytes((DATA/'LICENSE.txt').read_bytes())
print('Generated',len(ranges),'BMP vertical ranges and',len(fallbacks),'fallbacks')
