#!/usr/bin/env python3
"""Mechanically transcribe the pinned CP932 TVP declarations; never run C++.

The hosted build uses --check. Without --check this updates the two generated
source files. The default literal expressions, including __DATE__/__TIME__, are
preserved; this does not extract, interpret or format their message contents.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "native/tjs2/messages"
DECLARATION = re.compile(r"^TVP_MSG_DECL(_CONST)?\(\s*(TVP\w+)\s*,([\s\S]*?)\);", re.MULTILINE)


def generated_sources():
    manifest = json.loads((SOURCE / "manifest.json").read_text(encoding="utf-8"))
    entries = []
    for item in manifest["files"]:
        raw = (SOURCE / item["file"]).read_bytes()
        if len(raw) != item["bytes"] or hashlib.sha256(raw).hexdigest() != item["sha256"]:
            raise ValueError(f"Pinned TVP message source changed: {item['file']}")
        text = raw.decode("cp932").replace("\r\n", "\n")
        for match in DECLARATION.finditer(text):
            entries.append((match[2], not bool(match[1]), match[3].strip(),
                            item["file"], text[:match.start()].count("\n") + 1))
    names = [entry[0] for entry in entries]
    if len(set(names)) != len(names) or len(names) != 144:
        raise ValueError("Expected 144 distinct original TVP message holders")
    registered = [entry[0] for entry in entries if entry[1]]
    constants = [entry[0] for entry in entries if not entry[1]]
    if len(registered) != 138 or len(constants) != 6:
        raise ValueError("Original TVP registered/constant inventory changed")
    header = ("// Generated by scripts/generate-tvp-messages.py; do not edit.\n"
              "// Original KRKR2 2.32stable source, copyright W.Dee and contributors.\n"
              "// Provenance, original bytes and license: ../messages/manifest.json and README.md.\n"
              "// Literal expressions are transcoded from CP932 without changing their content.\n\n")
    native = header + "\n\n".join(
        f"// {file}:{line}\nTVP_MESSAGE({name}, {'true' if registered else 'false'},\n{body})"
        for name, registered, body, file, line in entries) + "\n"
    typescript = ("// Generated by scripts/generate-tvp-messages.py from fixed 2.32stable declarations.\n"
                  "// Native Japanese defaults live in TvpMessages.generated.inc; this is only the ID inventory.\n"
                  "// Provenance: native/tjs2/messages/manifest.json.\n\n")
    for variable, values in [("registeredTvpMessageIds", registered), ("constantTvpMessageIds", constants)]:
        typescript += "export const " + variable + " = [\n"
        typescript += "".join(f"  '{value}',\n" for value in values)
        typescript += "] as const\n\n"
    typescript += ("export const tvpMessageIds = [...registeredTvpMessageIds, ...constantTvpMessageIds] as const\n"
                   "export type TvpMessageId = typeof tvpMessageIds[number]\n")
    return {
        ROOT / "native/tjs2/include/TvpMessages.generated.inc": native,
        ROOT / "src/engine/system/tvp-message-ids.ts": typescript,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    for path, content in generated_sources().items():
        if options.check:
            if not path.exists() or path.read_bytes() != content.encode("utf-8"):
                raise SystemExit(f"Generated TVP message source differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content.encode("utf-8"))


if __name__ == "__main__":
    main()
